### ISSUE TITLE
Broken non-english search

### ISSUE THREAD

**Issue by wpresident** [misterpoop/jackett-metasearch#2]
With current version searching of cyrillic words compete broken - shows absolutely different words in results, etc
English words works perfect.

Can't wait new version of your work.

**Comment by sudozid** [comment]
hello, 

can you send screenshots? i think there maybe something wrong with jackett, my mod doesn't change anything in the backend. its just opening the "Manual Search" window of jackett by default.

https://i.ibb.co/gZZ8VJ4/jfjsd.png

**Comment by sudozid** [comment]
i'm on v0.18.729 btw

**Comment by sudozid** [comment]
i've updated the mod to show version number at bottom now

**Comment by wpresident** [comment]
Problem was from my side. Thank you for your project, don't stop.
